import { api } from '../utils/apiClient';
import type { Employee, PaginatedResponse } from './types';

// Depending on backend exact creation shape; omitting autogenerated fields
type CreateEmployeePayload = {
  employee_id: string;
  branch_id: number;
  designation_id: number;
  date_of_joining: string;
  first_name: string;
  last_name: string;
  email: string;
  phone_number: string;
};

type UpdateEmployeePayload = Partial<CreateEmployeePayload>;

export const employeesApi = {
  list: (params?: { page?: number; per_page?: number }) =>
    api.get<PaginatedResponse<Employee>>('/employees/', { params }),

  get: (employeeEid: string) =>
    api.get<Employee>(`/employees/${employeeEid}`),

  create: (data: CreateEmployeePayload) =>
    api.post<Employee>('/employees/', data),

  update: (employeeEid: string, data: UpdateEmployeePayload) =>
    api.patch<Employee>(`/employees/${employeeEid}`, data),

  manageSupervisor: (employeeEid: string, supervisorEid: string | null) =>
    api.post<Employee>(`/employees/${employeeEid}/manage_supervisor`, { eid: supervisorEid }),

  updateStatus: (employeeEid: string, is_active: boolean) =>
    api.patch<void>(`/employees/${employeeEid}/update_status`, { is_active }),
};
